### ISSUE TITLE
Some hidden Jitsi features may be desirable depending on the device used to access the application

### ISSUE THREAD

**Issue by sampaccoud** [openfun/jitsi-box#49]
**Is your feature request related to a problem? Please describe.**
A lot of Jitsi features are disabled on the application, to make it usable on a box with a small touch screen.
However, when we access the app with a laptop, or a tablet with a bigger screen, it would be better to get all the features.

**Describe the solution you'd like**
Disable features only on small screens ? But some of the features may be linked to the size of the screen (like "participants") while some features are linked to the environment around the browser (like "screen sharing")... so it is not easy to decide what to activate or not automatically...
An alternative may be to add a configuration panel to enable/disable each Jitsi feature manually on the application ?

**Comment by kudzimi** [comment]
Perhaps an easy way would be to add a button allowing the user to toggle between a basic interface and another one containing all the features. The basic interface would be the one by default. If the user wanted more features, they could just click the toggle button.
